/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (legacy alias for /health/live) */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe (k8s canonical name)
         * @description Identical semantics to `/health` — returns 200 as long as the
         *     process is up. Use this as the k8s `livenessProbe` target.
         *     For dependency reachability use `/health/ready`.
         */
        get: operations["getLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe (NATS + Postgres reachability)
         * @description Returns 200 with per-dependency status when all dependencies
         *     are reachable, 503 otherwise. Use this — not `/health` — as
         *     the orchestrator's readiness target so the service is removed
         *     from rotation during transient downstream blips without
         *     triggering a liveness restart.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics endpoint
         * @description Exposes the standard Prometheus text exposition format for the
         *     api binary. Compute and ingest expose their own /metrics on
         *     :9092 and :9091 respectively. The full metric catalog —
         *     including the alert rules paired with each — lives in
         *     deploy/prometheus/flowgreeks.rules.yml.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest full state snapshot for a symbol */
        get: operations["getSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/levels/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Key levels projection (cheap)
         * @description Just walls + flip + expected move from the latest snapshot. Use this when you don't need the full strike matrix.
         */
        get: operations["getLevels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * What-If Dealer Simulator
         * @description Runs the dealer-positioning simulator against the latest snapshot. Returns forced delta / notional plus top contributing strikes.
         */
        post: operations["postSimulate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a strategy against the historical dealer-state archive
         * @description Replays the `dealer_state_1s` archive over `[from, to)` and evaluates
         *     an entry/exit predicate pair built from the same triple
         *     (`kind`, `threshold`, `string_arg`) saved alert rules use.
         *
         *     Hard limits: range ≤ 31 days, 30s deadline, snapshots returned in
         *     ascending ts.
         */
        post: operations["postBacktestRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List alert rules for the current user (paginated) */
        get: operations["listAlertRules"];
        put?: never;
        /** Create or replace an alert rule */
        post: operations["upsertAlertRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an alert rule */
        delete: operations["deleteAlertRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example api */
            service: string;
        };
        ReadinessResponse: {
            /** @enum {string} */
            status: "ready" | "not_ready";
            /** @example api */
            service: string;
            /**
             * @example {
             *       "nats": {
             *         "ok": true
             *       },
             *       "postgres": {
             *         "ok": false,
             *         "error": "ping: connection refused"
             *       }
             *     }
             */
            deps: {
                [key: string]: {
                    ok?: boolean;
                    error?: string;
                };
            };
        };
        LevelsResponse: {
            /** Format: double */
            spot?: number;
            /** Format: double */
            zero_gamma?: number;
            /** Format: double */
            call_wall?: number;
            /** Format: double */
            put_wall?: number;
            /** Format: double */
            expected_mv?: number;
            /** Format: double */
            net_gex?: number;
            /** @description 0=UNKNOWN, 1=SHORT_GAMMA, 2=LONG_GAMMA, 3=NEUTRAL */
            regime?: number;
            /** Format: int64 */
            ts_ns?: number;
        };
        /** @description Per-second dealer state (same wire shape as `state.<sym>.gex`) */
        StateSnapshot: {
            /** Format: int64 */
            ts_ns?: number;
            /** @description 1=SPX, 2=NDX */
            symbol?: number;
            /** Format: double */
            spot?: number;
            /** Format: double */
            basis_smooth?: number;
            /** @example ESM6 */
            fut_front_sym?: string;
            /** Format: double */
            net_gex?: number;
            /** Format: double */
            zero_gamma?: number;
            /** Format: double */
            call_wall?: number;
            /** Format: double */
            put_wall?: number;
            /** Format: double */
            expected_mv?: number;
            regime?: number;
            dpi?: components["schemas"]["DPIBreakdown"];
            flow_pulse?: components["schemas"]["FlowPulse"];
            /** @description 1=WEAK, 2=RISING, 3=PEAK, 4=FADING, 5=PIN */
            charm_zone?: number;
            /** Format: double */
            charm_velocity_raw?: number;
            pin?: components["schemas"]["PinResult"];
            strikes?: components["schemas"]["StrikeRow"][];
        };
        DPIBreakdown: {
            /** Format: double */
            composite?: number;
            /** Format: double */
            net_gamma_sign?: number;
            /** Format: double */
            charm_velocity?: number;
            /** Format: double */
            vanna_sensitivity?: number;
            /** Format: double */
            time_to_close_decay?: number;
            /** Format: double */
            flow_concentration?: number;
        };
        FlowPulse: {
            /** Format: double */
            gamma?: number;
            /** Format: double */
            charm?: number;
            /** Format: double */
            vanna?: number;
            /** Format: double */
            total?: number;
        };
        PinResult: {
            active?: boolean;
            /** Format: double */
            window_mins?: number;
            /** Format: double */
            top_strike?: number;
            /** Format: double */
            top_probability?: number;
            candidates?: components["schemas"]["PinCandidate"][];
        };
        PinCandidate: {
            /** Format: double */
            strike?: number;
            /** Format: double */
            probability?: number;
            /** Format: double */
            gamma_strength?: number;
            /** Format: double */
            distance_factor?: number;
            /** Format: double */
            flow_persistence?: number;
            /** Format: double */
            time_factor?: number;
        };
        StrikeRow: {
            /**
             * Format: int32
             * @description YYYYMMDD
             */
            expiry?: number;
            /**
             * Format: int32
             * @description strike × 1000 (encode/decode helpers in feed package)
             */
            strike?: number;
            /** @description 1=CALL, 2=PUT */
            side?: number;
            /** Format: int64 */
            dealer_pos?: number;
            /** Format: double */
            iv?: number;
            /** Format: double */
            gamma?: number;
            /** Format: double */
            charm?: number;
            /** Format: double */
            vanna?: number;
            /** Format: double */
            gex_notional?: number;
        };
        SimulateRequest: {
            /**
             * Format: double
             * @description e.g. 0.01 = +1% spot move
             */
            spot_pct_change?: number;
            /** Format: double */
            duration_minutes?: number;
            /**
             * Format: double
             * @description e.g. 0.02 = +2 vol points
             */
            vol_pt_change?: number;
        };
        SimulateResponse: {
            /** @enum {string} */
            symbol?: "spx" | "ndx";
            /** Format: double */
            spot?: number;
            /** Format: double */
            new_spot?: number;
            /** Format: double */
            duration_years?: number;
            /** Format: double */
            forced_delta?: number;
            /** Format: double */
            forced_notional?: number;
            /** Format: double */
            charm_aid?: number;
            /** Format: double */
            net_pressure?: number;
            top_contributions?: components["schemas"]["StrikeContribution"][];
        };
        StrikeContribution: {
            /** Format: int32 */
            expiry?: number;
            /** Format: double */
            strike?: number;
            /** @enum {string} */
            side?: "C" | "P";
            /** Format: double */
            old_delta?: number;
            /** Format: double */
            new_delta?: number;
            /** Format: double */
            delta_change?: number;
            /** Format: double */
            forced_notional?: number;
        };
        BacktestRequest: {
            /** @enum {string} */
            symbol: "spx" | "ndx" | "SPX" | "NDX";
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /**
             * @default long
             * @enum {string}
             */
            direction: "long" | "short";
            /** Format: double */
            max_hold_min?: number;
            /**
             * Format: double
             * @default 0
             */
            cooldown_min: number;
            name?: string;
            entry: components["schemas"]["RuleSpec"];
            exit?: components["schemas"]["RuleSpec"] & unknown;
        };
        RuleSpec: {
            kind: components["schemas"]["RuleKind"];
            /** Format: double */
            threshold?: number;
            string_arg?: string;
        };
        /** @enum {string} */
        RuleKind: "dpi_above" | "dpi_below" | "charm_zone" | "regime" | "pin_prob_above" | "net_gex_above" | "net_gex_below";
        BacktestResponse: {
            strategy?: string;
            symbol?: string;
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
            count?: number;
            wins?: number;
            losses?: number;
            /** Format: double */
            win_rate?: number;
            /** Format: double */
            mean_return?: number;
            /** Format: double */
            stddev?: number;
            /** Format: double */
            sharpe?: number;
            /** Format: double */
            sortino?: number;
            /** Format: double */
            max_dd?: number;
            /** Format: double */
            total_return?: number;
            snapshots_evaluated?: number;
            trades?: components["schemas"]["Trade"][];
        };
        Trade: {
            /** Format: date-time */
            entry_ts?: string;
            /** Format: date-time */
            exit_ts?: string;
            /** Format: double */
            entry_spot?: number;
            /** Format: double */
            exit_spot?: number;
            /** @enum {string} */
            direction?: "long" | "short";
            /** Format: double */
            return_pct?: number;
            /** Format: double */
            held_sec?: number;
            exit_reason?: string;
        };
        AlertRule: {
            id: string;
            user_id?: string;
            /** @description 1=SPX, 2=NDX */
            symbol: number;
            kind: components["schemas"]["RuleKind"];
            /** Format: double */
            threshold?: number;
            string_arg?: string;
            /** Format: int64 */
            cooldown_ns?: number;
            sinks?: string[];
            enabled?: boolean;
        };
        AlertRuleList: {
            rules: components["schemas"]["AlertRule"][];
            /** @description Total rules matching the owner filter, pre-pagination. */
            total: number;
            offset: number;
            limit: number;
        };
    };
    responses: {
        /** @description Bad input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Compute hasn't published a snapshot yet */
        NoStateYet: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Underlying ticker (case-insensitive) */
        Symbol: "spx" | "ndx" | "SPX" | "NDX";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All deps healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description One or more deps unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus exposition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
    getSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Underlying ticker (case-insensitive) */
                symbol: components["parameters"]["Symbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest snapshot — same shape as `state.<sym>.gex` NATS payload */
            200: {
                headers: {
                    /** @description RFC3339 timestamp of the snapshot */
                    "X-Snapshot-Ts-Ns"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NoStateYet"];
        };
    };
    getLevels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Underlying ticker (case-insensitive) */
                symbol: components["parameters"]["Symbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projected levels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NoStateYet"];
        };
    };
    postSimulate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Underlying ticker (case-insensitive) */
                symbol: components["parameters"]["Symbol"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Simulator result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NoStateYet"];
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    postBacktestRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Strategy run summary + trade list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No state rows in range */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Backtest disabled (postgres unavailable at boot) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Backtest exceeded the 30s budget */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAlertRules: {
        parameters: {
            query?: {
                /** @description Page size, clamped to [1, 200] */
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated rule list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleList"];
                };
            };
        };
    };
    upsertAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRule"];
            };
        };
        responses: {
            /** @description Stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
